version = 0.1

[default.deploy.parameters]
stack_name = "CMSC471HelloStack"
resolve_s3 = true
s3_prefix = "CMSC471HelloStack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "LabRoleArn=\"<your-lab-role-arn-here>\""
image_repositories = []
